
--SUBJECT 會計科目檔

INSERT INTO public.SUBJECT (CODE,NAME) VALUES ('1000','收入');

INSERT INTO public.SUBJECT (CODE,NAME) VALUES ('1100','贊助');
INSERT INTO public.SUBJECT (CODE,NAME) VALUES ('1101','家人贊助');
INSERT INTO public.SUBJECT (CODE,NAME) VALUES ('1102','朋友贊助');
INSERT INTO public.SUBJECT (CODE,NAME) VALUES ('1103','同事贊助');

INSERT INTO public.SUBJECT (CODE,NAME) VALUES ('1200','薪資');
INSERT INTO public.SUBJECT (CODE,NAME) VALUES ('1201','主業薪資');
INSERT INTO public.SUBJECT (CODE,NAME) VALUES ('1202','兼職薪資');

INSERT INTO public.SUBJECT (CODE,NAME) VALUES ('1300','利息');
INSERT INTO public.SUBJECT (CODE,NAME) VALUES ('1301','活存利息');
INSERT INTO public.SUBJECT (CODE,NAME) VALUES ('1302','股票利息');
INSERT INTO public.SUBJECT (CODE,NAME) VALUES ('1303','基金利息');


INSERT INTO public.SUBJECT (CODE,NAME) VALUES ('2000','支出');

INSERT INTO public.SUBJECT (CODE,NAME) VALUES ('2100','伙食費');
INSERT INTO public.SUBJECT (CODE,NAME) VALUES ('2101','早餐');
INSERT INTO public.SUBJECT (CODE,NAME) VALUES ('2102','中餐');
INSERT INTO public.SUBJECT (CODE,NAME) VALUES ('2103','晚餐');
INSERT INTO public.SUBJECT (CODE,NAME) VALUES ('2104','飲料');
INSERT INTO public.SUBJECT (CODE,NAME) VALUES ('2105','宵夜');
INSERT INTO public.SUBJECT (CODE,NAME) VALUES ('2106','點心');

INSERT INTO public.SUBJECT (CODE,NAME) VALUES ('2200','交通費');
INSERT INTO public.SUBJECT (CODE,NAME) VALUES ('2201','大眾交通');
INSERT INTO public.SUBJECT (CODE,NAME) VALUES ('2202','加油費');
INSERT INTO public.SUBJECT (CODE,NAME) VALUES ('2203','保養費');
INSERT INTO public.SUBJECT (CODE,NAME) VALUES ('2204','計程車');
