
--日記帳 年月資料

CREATE OR REPLACE VIEW VIEW_JOURNAL_RECORD_YEAR_MONTH AS
SELECT DISTINCT 
    EXTRACT(YEAR FROM TX_TIME) AS YEAR,
    EXTRACT(MONTH FROM TX_TIME) AS MONTH
FROM JOURNAL_RECORD;

COMMENT ON VIEW public.VIEW_JOURNAL_RECORD_YEAR_MONTH IS 'VIEW日記帳年月資料檔';
COMMENT ON COLUMN public.VIEW_JOURNAL_RECORD_YEAR_MONTH.YEAR IS '年';
COMMENT ON COLUMN public.VIEW_JOURNAL_RECORD_YEAR_MONTH.MONTH IS '月';
